config/routes.rb
AssetsManagement::Application.routes.draw do
  resources :invoices do
    get 'filter', :on => :collection
  end
  resources :items do
    collection do
      get 'stock'
      get 'faulty'
      get 'returned'
    end
    member do
      get 'toggle_stock'
      get 'toggle_faulty'
      get 'toggle_returned'
    end
  end
  resources :devices do
    collection do
      get 'stock'
      get 'scrap'
      get 'faulty'
      get 'deleted'
      get 'filter'
      get 'returned'
    end
    member do
      get 'toggle_stock'
      get 'toggle_deleted'
      get 'toggle_faulty'
      get 'toggle_returned'
    end
  end

  resources :client_assets do
    collection do
      get 'deleted'
    end
  end

  resources :quotations do
    get '/all_quotations', :on => :collection, :to => "quotations#list_all_quotations"
  end

  resources :asset_requests
   resources :vendors do
    resources :computers
    resources :quotations
   end

  resources :employee_associations

  resources :employees do
    collection do
      get 'new_joinees'
      get 'deleted'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'home#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :deleted, :deleted_at, :faulty, :faulty_date, :invoice_id, :name, :os, :os_version, :provider, :repaired_date, :returned, :returned_date, :scrap, :stock, :vendor_id, :warranty
  
  #ASSOCIATIONS

  belongs_to :vendor
  has_many :client_assets, as: :referenceable
  has_many :employee_associations, as: :associable
  
  #VALIDATIONS

  validates :name, presence: true
  
  PROVIDER = ["Clarion","Client"]
  
  # Scope goes here #
  scope :inactive, where(:deleted => true)
  scope :active, where("deleted IS NULL OR deleted = ?", false)
  scope :stock, where(:stock => true)
  scope :scrap, where(:scrap => true)
  scope :faulty, where(:faulty => true)
  scope :returned, where(:returned => true)
  default_scope order('created_at DESC')

  # Class method goes here #
  def self.active_and_stock
    active.stock
  end

  def self.active_and_scrap
    active.scrap
  end

  def self.active_and_faulty
    active.faulty
  end

  def self.active_and_returned
    active.returned
  end
  
  # Class method for search #
  def self.search(search = nil,action)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      if action == "deleted"
        inactive
      elsif action == "stock"
        active.stock
      elsif action == "scrap"
        active.scrap
      elsif action == "faulty"
        active.faulty
      elsif action == "returned"
        active.returned
      else
        active
      end
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_vendors
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.active.search(params[:search],params[:action]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # To filter devices based on selected vendor name #
  def filter
    if !params[:vendors].blank? and params[:vendors] != "All"
      @devices = Device.active.where(vendor_id: params[:vendors]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    else
      @devices = Device.active.search(params[:search],params[:action]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # Devices in stock #
  def stock
    @devices = Device.active_and_stock.search(params[:search],params[:action]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # Scarp devices #
  def scrap
    @devices = Device.active_and_scrap.search(params[:search],params[:action]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # Faulty devices #
  def faulty
    @devices = Device.active_and_faulty.search(params[:search],params[:action]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # Returned devices #
  def returned
    @devices = Device.active_and_returned.search(params[:search],params[:action]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # InActive devices #
  def deleted
    @devices = Device.inactive.search(params[:search],params[:action]).order(sort_column("Device", 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: "#{@device.name} was successfully created." }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: "#{@device.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    name = @device.name
    @device.deleted = true
    @device.deleted_at = Time.now
    @device.save
    respond_to do |format|
      format.html { redirect_to devices_url, notice: "#{name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  # To toggle stock flag #
  def toggle_stock  
    @device = Device.find(params[:id])  
    @device.toggle!(:stock)  
  end 

  # To toggle stock flag #
  def toggle_deleted  
    @device = Device.find(params[:id])  
    @device.toggle!(:deleted)  
    @device.deleted_at = nil
    @device.save
    @devices = Device.inactive
  end

  # To toggle faulty flag #
  def toggle_faulty
    @device = Device.find(params[:id])  
    @device.toggle!(:faulty)  
  end

  # To toggle returned flag #
  def toggle_returned
    @device = Device.find(params[:id])  
    @device.toggle!(:returned) 
  end
 
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_devices.html.erb
<%- model_class = Device -%>
<% if @devices and @devices.count > 0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable model_class, "name" %></th>
      <th><%= model_class.human_attribute_name(:vendor_id) %></th>
      <th><%= model_class.human_attribute_name(:invoice_id) %></th>
      <th><%= model_class.human_attribute_name(:os) %></th>
      <th><%= model_class.human_attribute_name(:os_version) %></th>
      <th><%= model_class.human_attribute_name(:warranty) %></th>
      <th><%= model_class.human_attribute_name(:provider) %></th>
      <% if params[:action] == "index" or params[:action] == "filter" %>
      <th><%= model_class.human_attribute_name(:scrap) %></th>
      <th><%= model_class.human_attribute_name(:stock) %></th>
      <th><%= model_class.human_attribute_name(:faulty) %></th>
      <th><%= model_class.human_attribute_name(:returned) %></th>
      <% end %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr id="tr_<%= device.id %>">
        <td><%= link_to device.name, device_path(device) %></td>
        <td><%= link_to device.vendor.name, vendor_path(device.vendor.id) %></td>
        <td><%= device.invoice_id %></td>
        <td><%= device.os %></td>
        <td><%= device.os_version %></td>
        <td><%= device.warranty %></td>
        <td><%= device.provider %></td>
        <% if params[:action] == "index" or params[:action] == "filter" %>
          <td><%= device.scrap %></td>
          <td><%= link_to stock_link_text(device), toggle_stock_device_path(device),   
                :remote => true,:id => "stock_link_#{device.id}" %></td>
          <td><%= link_to faulty_link_text(device), toggle_faulty_device_path(device),   
                :remote => true,:id => "faulty_link_#{device.id}" %></td>
          <td><%= link_to returned_link_text(device), toggle_returned_device_path(device),   
                :remote => true,:id => "returned_link_#{device.id}" %></td>
        <% end %>
        <td class="action-td">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_device_path(device), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")), 
                        device_path(device), 
                        :method => :delete, 
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                        :class => 'btn btn-mini btn-danger' unless params[:action] == "deleted" %>
          <%= link_to active_link_text(device), toggle_deleted_device_path(device), :remote => true , :class => 'btn btn-mini' if params[:action] == "deleted" %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tr>
    <td colspan="8" style="background-color: #FFFFFF;"> 
      <div style="float:right;">
        <%= will_paginate @devices, renderer: BootstrapPagination::Rails %>
      </div>
    </td>
  </tr>
</table>
<% else %>
 <div>
    Record Not Found
  </div >
<% end %>

app/views/devices/_filter.html.erb
<%= form_tag filter_devices_path, :method => :get do %>
  <div class="control-group">
    <div class="controls">
      <%= label_tag "vendors","Filter By Vendors:", :class => 'control-label' %>
      <%= select_tag "vendors", options_for_select(@vendors.map { |v| [ v.name, v.id ] }.insert(0,"All"), :selected => params[:vendors]) %>
      <%= submit_tag "Filter", :name => nil , :class => 'btn btn-primary'%>
    </div>
  </div>
<% end %>

app/views/devices/_form.html.erb
<%= form_for @device, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>
      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
      <span class="error-indicator">*</span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vendor_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :vendor_id, @vendors.map { |v| [ v.name, v.id ] }%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :invoice_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :invoice_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :os, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :os, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :os_version, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :os_version, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :warranty, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :warranty, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :provider, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :provider, options_for_select(Device::PROVIDER)%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :scrap, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :scrap, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stock, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :stock, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :faulty, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :faulty, :class => 'check_box' %>
    </div>
  </div>
  <span id="ref_faulty_date">
    <div class="control-group">
      <%= f.label :faulty_date, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_select :faulty_date, {:include_blank => true, :default => nil}, :class => 'datetime_select' %>
      </div>
    </div>
   </span>
  <div class="control-group">
    <%= f.label :returned, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :returned, :class => 'check_box' %>
    </div>
  </div>
  <span id="ref_returned_date">
  <div class="control-group">
    <%= f.label :returned_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :returned_date, {:include_blank => true, :default => nil}, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :repaired_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :repaired_date, {:include_blank => true, :default => nil}, :class => 'datetime_select' %>
    </div>
  </div>
  </span>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                devices_path, :class => 'btn' %>
  </div>
<% end %>

app/views/devices/_search.html.erb
<div class="control-group">
  <div class="controls">
    <%= label_tag :search, "Search by Device Name:", :class => 'control-label' %>
    <%= text_field_tag :search, params[:search], :class => 'number_field' %>
    <%= submit_tag "Search", :name => nil , :class => 'btn btn-primary'%>
  </div>
</div>

app/views/devices/edit.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/filter.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag devices_path, :method => :get do %>
  <%= render 'search' %>
<% end %>
<%= render 'filter' %>
<%= render 'devices' %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/index.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= form_tag devices_path, :method => :get do %>
  <%= render 'search' %>
<% end %>
<%= render 'filter' %>
<%= render 'devices' %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/new.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/returned.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Returned Devices" %></h1>
</div>
<%= form_tag returned_devices_path, :method => :get do %>
  <%= render 'search' %>
<% end %>
<%= render 'devices' %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/scrap.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Scrap Devices" %></h1>
</div>
<%= form_tag scrap_devices_path, :method => :get do %>
  <%= render 'search' %>
<% end %>
<%= render 'devices' %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/show.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vendor_id) %>:</strong></dt>
  <dd><%= @device.vendor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:invoice_id) %>:</strong></dt>
  <dd><%= @device.invoice_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:os) %>:</strong></dt>
  <dd><%= @device.os %></dd>
  <dt><strong><%= model_class.human_attribute_name(:os_version) %>:</strong></dt>
  <dd><%= @device.os_version %></dd>
  <dt><strong><%= model_class.human_attribute_name(:warranty) %>:</strong></dt>
  <dd><%= @device.warranty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:provider) %>:</strong></dt>
  <dd><%= @device.provider %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scrap) %>:</strong></dt>
  <dd><%= @device.scrap %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock) %>:</strong></dt>
  <dd><%= @device.stock %></dd>
  <dt><strong><%= model_class.human_attribute_name(:faulty) %>:</strong></dt>
  <dd><%= @device.faulty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:faulty_date) %>:</strong></dt>
  <dd><%= @device.faulty_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:returned) %>:</strong></dt>
  <dd><%= @device.returned %></dd>
  <dt><strong><%= model_class.human_attribute_name(:returned_date) %>:</strong></dt>
  <dd><%= @device.returned_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:repaired_date) %>:</strong></dt>
  <dd><%= @device.repaired_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              devices_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_device_path(@device), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              device_path(@device),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/devices/toggle_deleted.js.erb
<% if @devices.count > 0 %>
  $("#tr_<%= @device.id %>").remove();
<% else %>
  $("#deleted_div").html("<%= escape_javascript(render(:partial => 'devices')).html_safe %>");
<% end %>

app/views/devices/toggle_faulty.js.erb
$("#faulty_link_<%= @device.id %>").text("<%= faulty_link_text(@device) %>");  
$("#faulty_link_<%= @device.id %>").effect("highlight"); 

app/views/devices/toggle_returned.js.erb
$("#returned_link_<%= @device.id %>").text("<%= returned_link_text(@device) %>");  
$("#returned_link_<%= @device.id %>").effect("highlight"); 
 