config/routes.rb
AssetsManagement::Application.routes.draw do
  resources :invoices do
    get 'filter', :on => :collection
  end
  resources :items do
    collection do
      get 'stock'
      get 'faulty'
      get 'returned'
    end
    member do
      get 'toggle_stock'
      get 'toggle_faulty'
      get 'toggle_returned'
    end
  end
  resources :devices do
    collection do
      get 'stock'
      get 'scrap'
      get 'faulty'
      get 'deleted'
      get 'filter'
      get 'returned'
    end
    member do
      get 'toggle_stock'
      get 'toggle_deleted'
      get 'toggle_faulty'
      get 'toggle_returned'
    end
  end

  resources :client_assets do
    collection do
      get 'deleted'
    end
  end

  resources :quotations do
    get '/all_quotations', :on => :collection, :to => "quotations#list_all_quotations"
  end

  resources :asset_requests
   resources :vendors do
    resources :computers
    resources :quotations
   end

  resources :employee_associations

  resources :employees do
    collection do
      get 'new_joinees'
      get 'deleted'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<br />
<% if current_user  %>
<ul>
  <li><%= link_to "Manage Vendors", vendors_path %></li>
  <li><%= link_to "Manage Items", items_path %></li>
  <li><%= link_to "Manage Item Requests", asset_requests_path %></li>
  <li><%= link_to "Manage Invoices", invoices_path %></li>
  <li><%= link_to "Manage Employees", employees_path %></li>
</ul>
<% end %>