config/routes.rb
AssetsManagement::Application.routes.draw do
  resources :invoices do
    get 'filter', :on => :collection
  end
  resources :items do
    collection do
      get 'stock'
      get 'faulty'
      get 'returned'
    end
    member do
      get 'toggle_stock'
      get 'toggle_faulty'
      get 'toggle_returned'
    end
  end
  resources :devices do
    collection do
      get 'stock'
      get 'scrap'
      get 'faulty'
      get 'deleted'
      get 'filter'
      get 'returned'
    end
    member do
      get 'toggle_stock'
      get 'toggle_deleted'
      get 'toggle_faulty'
      get 'toggle_returned'
    end
  end

  resources :client_assets do
    collection do
      get 'deleted'
    end
  end

  resources :quotations do
    get '/all_quotations', :on => :collection, :to => "quotations#list_all_quotations"
  end

  resources :asset_requests
   resources :vendors do
    resources :computers
    resources :quotations
   end

  resources :employee_associations

  resources :employees do
    collection do
      get 'new_joinees'
      get 'deleted'
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => 'home#index'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :address, :city, :contact_no, :deleted, :deleted_at, :email, :fax_no, :mobile_no, :name, :state, :website

  #ASSOCIATIONS

  has_many :computers, :conditions => ('deleted IS NULL or deleted = false'), :dependent => :destroy
  has_many :asset_requests, :dependent => :destroy
  has_many :quotations, :dependent => :destroy
  has_many :devices
  has_many :items, :dependent => :destroy
  has_many :invoices, :dependent => :destroy
  
  #VALIDATIONS

  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :website, presence: true
  validates :website, uniqueness: true


  #SCOPES

  scope :active_vendors, where("deleted IS NULL OR deleted = ?", false)


  #METHODS
  
  def self.search(search = nil,action)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      if action == "index"
       active_vendors
      end
    end
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_filter :authenticate_user!

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.active_vendors.search(params[:search],params[:action]).order(sort_column('Vendor', 'name') + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 2)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vendors }
    end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/new
  # GET /vendors/new.json
  def new
    @vendor = Vendor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vendor }
    end
  end

  # GET /vendors/1/edit
  def edit
    @vendor = Vendor.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(params[:vendor])

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice:  "#{@vendor.name} was successfully added." }
        format.json { render json: @vendor, status: :created, location: @vendor }
      else
        format.html { render action: "new" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @vendor = Vendor.find(params[:id])

    respond_to do |format|
      if @vendor.update_attributes(params[:vendor])
        format.html { redirect_to @vendor, notice: "#{@vendor.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor = Vendor.find(params[:id])
    vendor_name = @vendor.name
    @vendor.deleted = true
    @vendor.deleted_at = Time.now
    @vendor.save

    respond_to do |format|
      format.html { redirect_to vendors_url, notice: "#{vendor_name} was successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for @vendor, :html => { :class => 'form-horizontal' } do |f| %>

 <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this computer from being saved:</h2>
      <ul>
      <% @vendor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
      <span class="error-indicator">*</span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
      <span class="error-indicator">*</span>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :contact_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :contact_no, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fax_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :fax_no, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mobile_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :mobile_no, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website, :class => 'text_field' %>
      <span class="error-indicator">*</span>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vendors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vendors/index.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= form_tag vendors_path, :method => :get do %>
  <div class="control-group">
    <%= label_tag :search, "Search by Name:", :class => 'control-label' %>
    <div class="controls">
      <%= text_field_tag :search, params[:search], :class => 'number_field' %>
      <%= submit_tag "Search", :name => nil , :class => 'btn btn-primary'%>
    </div>
  </div>
<% end %>

<p><%= link_to 'List of all quotations', all_quotations_quotations_path, :class => 'btn btn-primary' %>
<%= link_to 'List of all Invoices', invoices_path, :class => 'btn btn-primary' %></p>
<p><%= link_to 'Add Vendor', new_vendor_path, :class => 'btn btn-primary' %></p>

<% if @vendors and @vendors.count > 0 %>
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th><%= sortable model_class, "name" %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <!-- <th><%= model_class.human_attribute_name(:address) %></th> -->
        <th><%= model_class.human_attribute_name(:city) %></th>
        <th><%= model_class.human_attribute_name(:state) %></th>
        <th><%= model_class.human_attribute_name(:contact_no) %></th>
        <th><%= model_class.human_attribute_name(:fax_no) %></th>
        <th><%= model_class.human_attribute_name(:mobile_no) %></th>
        <th><%= model_class.human_attribute_name(:website) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @vendors.each do |vendor| %>
        <tr>
          <td><%= link_to vendor.name, vendor %></td>
          <td><%= vendor.email %></td>
          <!-- <td><%= vendor.address %></td> -->
          <td><%= vendor.city %></td>
          <td><%= vendor.state %></td>
          <td><%= vendor.contact_no %></td>
          <td><%= vendor.fax_no %></td>
          <td><%= vendor.mobile_no %></td>
          <td><%= vendor.website %></td>
          <td class="action-td">
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vendor_path(vendor), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vendor_path(vendor),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tr>
      <td colspan="8" style="background-color: #FFFFFF;">
        <div style="float:right;">
          <%= will_paginate @vendors, renderer: BootstrapPagination::Rails %>
        </div>
      </td>
    </tr>
  </table>
<% else %>
  <div >
    Record Not Found
  </div >
<% end %>

<%= link_to 'Back', :back, :class => 'btn' %>

app/views/vendors/new.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vendors/show.html.erb
<%- model_class = Vendor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div style="float:right;">
  <ul>
    <li><%= link_to "Computers", vendor_computers_path(@vendor) %></li>
    <li>Assets</li>
    <li>Devices</li>
    <li>Accessories</li>
    <li><%= link_to "Quotations", vendor_quotations_path(@vendor) %></li>
    <li>Invoices</li>
    <li>Accessories</li>
  </ul>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @vendor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @vendor.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @vendor.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @vendor.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @vendor.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_no) %>:</strong></dt>
  <dd><%= @vendor.contact_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fax_no) %>:</strong></dt>
  <dd><%= @vendor.fax_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile_no) %>:</strong></dt>
  <dd><%= @vendor.mobile_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @vendor.website %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              :back, :class => 'btn'  %>
</div>